name: Rust CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --verbose

  publish:
    name: Cargo Publish
    uses: ryohidaka/action-cargo-publish@be41ba19145bd21857b40009c3fc6512748be4be
    with:
      # The token to publish to crates.io.
      token: ${{ secrets.CRATES_TOKEN }}
      # If true, run cargo publish with the --dry-run flag.
      dry-run: true
    needs: [test]
